server:
 port: 8080
 servlet:
  encoding:
   charset: UTF-8
   
springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    operations-sorter: alpha # alpha(알파벳 오름차순), method(HTTP메소드순)
    tags-sorter: alpha # 태그 정렬 기준
    path: /swagger-ui.html # html 문서 접속 경로
    disable-swagger-default-url: true
    doc-expansion: none # tag, operation 펼치는 방식

spring:
 config.import: sm://
 redis:
    port: 6379
    host: ${sm://redis-url}
 datasource:
  master:
   hikari:
    driver-class-name: org.postgresql.Driver
    jdbc-url: ${sm://jdbc-url}
    username: app_user
    password: ${sm://db-pwd}
    read-only: false
  slave:
   hikari:
    driver-class-name: org.postgresql.Driver
    jdbc-url: ${sm://jdbc-url}
    username: app_user
    password: ${sm://db-pwd}
    read-only: true
 sql:
  init:
   mode: EMBEDDED
 jpa:
  database: postgresql
  database-platform: org.hibernate.dialect.PostgreSQLDialect
  defer-datasource-initialization: true
  show-sql: true
  hibernate:
   ddl-auto: validate
 mvc:
  pathmatch:
   matching-strategy: ANT_PATH_MATCHER

logging:
  pattern.console: "%clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr([${LOG_LEVEL_PATTERN:%5p}]) %clr([%X{userId}]) %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
  level:
    root: info
    com.member: debug
